axis_linear:
  x: 1
  y: 0
scale_linear:
  x: 0.4
  y: 0.4
scale_linear_turbo:
  x: 1.0
  y: 1.0
axis_angular:
  yaw: 3
scale_angular:
  yaw: 1.0
scale_angular_turbo:
  yaw: 1.5

enable_button: 4
enable_turbo_button: 5